### ISSUE TITLE
[core] Keyboard config not restored properly after running any raylib program

### ISSUE THREAD

**Issue by alanbork** [raysan5/raylib#1769]
There seems to be some kind of regression on the keyboard handling code for platform_RPI, as it seems like the problem I'm having was might have been fixed in https://github.com/raysan5/raylib/pull/785? It's very hard to trace what happened to that code in the modern release of raylib; the #defines don't match up.

To reproduce: 

run any raylib example program, then try to start nano:

%nano
Received SIGHUP or SIGTERM
%

but if you compile the same program under platform_drm there's no problem, the code works fine (if somewhat slowly on the pi0 which is why I prefer platform_RPI.

**Comment by alanbork** [comment]
Doing some poking, it seems the issue is that

```
// Restore default keyboard input
static void RestoreKeyboard(void)

    // Reset to default keyboard settings
    tcsetattr(STDIN_FILENO, TCSANOW, &CORE.Input.Keyboard.defaultSettings);

    // Reconfigure keyboard to default mode
    ioctl(STDIN_FILENO, KDSKBMODE, CORE.Input.Keyboard.defaultMode);
} 
```

does not also restore the flags back to what they were originally, and this leaves stdin nonblocking. force it to be blocking again or restore the flags and it works right. I'm not sure why this is fine in platform_drm but it's definitely the issue in platform_rpi.

the proposal would be something like this:

// Restore default keyboard input
static void RestoreKeyboard(void)
{
   fcntl(STDIN_FILENO, F_SETFL, savedflags); // should be in CORE.x.y.z obviously. 

    // Reset to default keyboard settings
    tcsetattr(STDIN_FILENO, TCSANOW, &CORE.Input.Keyboard.defaultSettings);

    // Reconfigure keyboard to default mode
    ioctl(STDIN_FILENO, KDSKBMODE, CORE.Input.Keyboard.defaultMode);
}

I haven't tested this fix anywhere other than platform_rpi, maybe it breaks something on one of the other platforms.

**Comment by alanbork** [comment]
there's a perl one-liner to fix stdin in case this doesn't get fixed in raylib:

perl -MFcntl -e 'fcntl STDIN, F_SETFL, fcntl(STDIN, F_GETFL, 0) & ~O_NONBLOCK'

(from https://unix.stackexchange.com/questions/437409/problems-caused-by-stdin-set-to-non-blocking-mode)

**Comment by raysan5** [comment]
@alanbork Feel free to send a PR with the `RestoreKeyboard()` fix.

**Comment by alanbork** [comment]
I'm a bit hesitant to submit a patch as I still don't understand why
platform_drm doesn't have this problem. Somebody who understands the input
system better should take a look.

**Comment by chriscamacho** [comment]
I really wish raylib had a standard OS interface, adding and maintaining "drivers" for each platform (with their own source unit) would be much simpler, one way to do it would be how GLFW does it - yes it would be some work, but it need not all be done at once - all these #ifdefs really are getting out of hand it makes tracking down issues much harder than it needs to be.

Some consultation with the community at large and some proper planning for this would be well worth the time and make a much more robust system.

**Comment by alanbork** [comment]
With the right tools ie vs code it iz possible to make it pretty clear
which if defs are applicable.

while I agree that the current system is kind of a challenge, the amount of
effort it would take to re-architect everything seems pretty high.

the issue in this particular case is not so much which code is active as
understanding why there would be any difference between the two platforms
given how the code overlap is almost 100% as far as I can tell. Separating
them out into separate modules wouldn't really help with that question, I
think?

**Comment by kernelkinetic** [comment]
`RestoreKeyboard()` (and the preceding `InitKeyboard()`) is only called if ` SUPPORT_SSH_KEYBOARD_RPI` is defined. Maybe that's the reason why it works for you on `PLATFORM_DRM` but not on `PLATFORM_RPI`, @alanbork?

**Comment by alanbork** [comment]
my reading of the makefile is that  SUPPORT_SSH_KEYBOARD_RPI  is enabled on
both platform_drm and platform_dri. And ssh keyboard does work on platform
drm with no code changes.

**Comment by raysan5** [comment]
@alanbork I'm afraid I can't reproduce this issue. I tried:

1. Run raylib example `core_basic_window`
2. Exit example
3. Run `nano`
4. Write some text file on nano

I tried it on CLI, no XWindow desktop, PLATFORM_RPI. 
I tried with a keyboard directly connected to RPI and also through SSH connection.

It worked on both cases for me.

**Comment by alanbork** [comment]
some clarification:

this only occurs on a real keyboard without and SSH involved. I observe it on my rpi0, with the latest raylib. it is always fixed by the one-liner 

perl -MFcntl -e 'fcntl STDIN, F_SETFL, fcntl(STDIN, F_GETFL, 0) & ~O_NONBLOCK'

after running any raylib example.  There's something odd about it, though because I don't see the problem with platform_drm and there's no good reason to explain why. I guess we'll have to wait until somebody else can replicate this problem...

**Comment by raysan5** [comment]
@alanbork Did you try recompiling raylib commenting `SUPPORT_SSH_KEYBOARD_RPI` on `config.h`?

Also noted that `PLATFORM_DRM` uses `InitTerminal()/RestoreTerminal()` instead of `InitKeyboard()/RestoreKeyboard()`.

**Comment by raysan5** [comment]
Keyboard mode has been reviewed on `PLATFORM_RPI` to use same method than `PLATFORM_DRM`, I'm not sure if it can have side effects... Please, let me know if problem persists.
