### ISSUE TITLE
[rcore][drm] `GetTouchPointCount()` returns 1 when screen is not touched

### ISSUE THREAD

**Issue by larry104** [raysan5/raylib#4842]
Just did a git pull to get the latest; compiled on a RaspberryPi 3 with make PLATFORM=PLATFORM_DRM

To reproduce just add to the core_input_multitouch.c a statement to print tCount and compile and run it.

When touching the screen first with your index finger when with your thumb  and then releasing the index finger and after that the thumb the tCount will still show 1 even though nothing touches the screen anymore.

**Comment by maiconpintoabreu** [comment]
Hi @larry104 looks like this behaviour is provoked by 

`PollInputEvents(void)`
...
`CORE.Input.Touch.position[0] = CORE.Input.Mouse.currentPosition;`
And `rcore_drm` is checking if position is different than 0 instead of keeping the `CORE.Input.Touch.pointCount` based on events
```
        // Update touch point count
        CORE.Input.Touch.pointCount = 0;
        for (int i = 0; i < MAX_TOUCH_POINTS; i++)
        {
            if (CORE.Input.Touch.position[i].x >= 0) CORE.Input.Touch.pointCount++;
        }
```

I do not have how to test it so I cannot try to fix it.

**Comment by MUL7ii** [comment]
@raysan5 I have made a PR #5279 could you look into it , if there are any changes let me know.

**Comment by CrackedPixel** [comment]
@larry104 @raysan5 can this be closed? the PR was merged

**Comment by larry104** [comment]
I don't think these issues are related nor does the  CORE.Input.Touch.pointCount = 0 fix the reported issue. You can check with the multitouch example core_input_multitouch.c. 

1) When you touch the screen with one finger and stop moving the finger around GetTouchPointCount() get's reset to 0 but the moment you start moving your finger again it gets back to 1.

2) If you touch the screen with first one finger then add the second. Now lift of the first and GetTouchPointCount()  will be still 2 (of course when moving the finger around)

It looks to me touchpoints do not get tracked properly in general especially when you don't have any movement.

Let me know if you need more explanation or want me to do tests or a take video  for print any debug info while touching.

**Comment by MUL7ii** [comment]
@larry104 I made changes could you check the pr merged and test it?

**Comment by larry104** [comment]
I only see the master branch which was updated 7 hours ago as of this writing .. are you talking about that? if yes, no changes in there.

**Comment by MUL7ii** [comment]
@larry104 check this #5279 PR

**Comment by larry104** [comment]
Yes, I compiled against that which is in the latest master branch. I confirmed by checking rcore_drm.c. But it does not solve the problem I am reporting.

**Comment by MUL7ii** [comment]
@larry104 can I have more more detials?

**Comment by MUL7ii** [comment]
@larry104 I have made some changes in my forked repo test branch https://github.com/MULTidll/raylib/tree/test could you also check that once?

**Comment by larry104** [comment]
When I print tCount = GetTouchPointCount(); I see the following:

The following was tested with the latest commit of the master branch as of this morning:
0: when screen is not touched
0: when touched and keep finger on the screen (that should show 1, and only when I lift the finger off the screen it should go back to 0)
0/1: when touching and constantly moving the finger, but it flickers so it's sometimes 1 and sometime 0.


Your fork shows the following:
0: when screen is not touched
0/1 when touched and keep finger on the screen (flickers randomly between 0 and 1)
1: when touching and constantly moving the finger. 

Both versions fail when it comes to touching with lets say 3 fingers (tCount=3) (constantly moving them around) and then removing one of the fingers. tCount=2 but it seems that touchPositions has only one value of the first touchpoint. 

Note: all tested with core_input_multitouch.c in from the examples (I just added printing tCount)

**Comment by MUL7ii** [comment]
@larry104 sorry for the late response, I have updated the rcore_drm.c  in test branch of my fork https://github.com/MULTidll/raylib/tree/test could you check if this way works?

**Comment by larry104** [comment]
It is much much better now. Number of touch points are correctly detected and no more flickering of the number of touchpoints. But there are still some issue. If I touch the screen with 5 fingers. An lift off all 5 again sometimes there is still one touchpoint active without anything touched. It happens in about 8 out of 10 cases. The second problem is if touch with 5 fingers and move them around, then lift one finger off and start moving the remaining 4 fingers one of the touchpoints does not move anymore if that makes sense.

**Comment by MUL7ii** [comment]
@larry104 added cleanup now try testing it https://github.com/MULTidll/raylib/tree/test

**Comment by larry104** [comment]
That made it some how worse. Now if I touch and keep touching without moving touchpoints disappear after ~2 seconds. If I keep my fingers moving they don't disappear.

**Comment by MUL7ii** [comment]
@larry104 could you try now https://github.com/MULTidll/raylib/tree/test

**Comment by larry104** [comment]
the problem with disappearing touchpoints is solved but now the following: lets say I touch the screen with 3 fingers and remove 1 finger but 2 disappear.  Dependent on which of the one finger I remove strange things happen e,g  the yellow circle under the finger pops up somewhere else. It would be easier to attach a short video ;-)

**Comment by MUL7ii** [comment]
try latest commit https://github.com/MULTidll/raylib/tree/test , also a short video would help could you attach some link?

**Comment by larry104** [comment]
See if that works for you https://youtu.be/RxKrflh3CDc

**Comment by larry104** [comment]
Sorry, I just noticed the first video I made was without your last updates.  This https://youtu.be/eqMmuhYIF-s is after your latest checkin.

**Comment by MUL7ii** [comment]
made few changes again https://github.com/MULTidll/raylib/tree/test, what is the debug showing now?

**Comment by larry104** [comment]
https://youtu.be/LWTS1u2FuH8 There is still an issue when releasing the first touchpoint and adding it back see video. Also even though the screen supports 10 touchpoints and the max touch points is set to 10 (#define MAX_TOUCH_POINTS 10) I only get 8 touchpoints.

**Comment by MUL7ii** [comment]
https://github.com/MULTidll/raylib/tree/test, could you debug?, and regarding the max touch points it was hardcoded in config.h to 8 so even if you define it elsewhere, it won't change. Temporarily, I have increased it to 10

**Comment by larry104** [comment]
The default should probably be 10 since most systems have 10 touchpoints. 
Here the video. There are still problems when removing and adding back the first touchpoint.
https://youtu.be/mC_8CX93KJU

**Comment by MUL7ii** [comment]
oh alright then it has been set to 10, https://github.com/MULTidll/raylib/tree/test, could you debug now?.

**Comment by larry104** [comment]
There is still the problem if you remove the first touchpoint and add it back ... https://youtu.be/P6Vl5dVnv7E if you remove others than the first it all works fine (see video)

**Comment by MUL7ii** [comment]
I have made the changes to fix that first touchpoint issue ig it should work now https://github.com/MULTidll/raylib/tree/test, try debugging now

**Comment by larry104** [comment]
Unfortunately, there is still the same issue. https://youtu.be/zdNr8gTI0jg Is there a reason why the touchpoints get renumbererd? Eg. I touch 1,2,3 remove finger 2, the remaining get renumbered to 1,2 which is correct but when I add one in again instead the new one gets 3 it gets 2 and the first 2 get renumbered again. The video shows what I mean.

**Comment by raysan5** [comment]
@larry104 @MULTidll It's been a while not using the touch system, I have no touch display at the moment for testing, but as far as I remember, the issue was considering the touch points as a simple count into an array, using the index as the ID. 

The right approach should be considering every touch with a unique ID, independently of the index position in the array of touch points; I mean, points can be reordered inside the array but the original touch point id should not change. That will allow tracking each touch state as an independent element.

**Comment by MUL7ii** [comment]
@raysan5 Oh okay got it, so by using the event.value it should be fixed right?, I have made the changes https://github.com/MULTidll/raylib/tree/test 
@larry104 could you try debugging now?

**Comment by larry104** [comment]
No, doesn't change anything. Once you remove the first (and only the first) touchpoint and add it back it's coordinate is all over the place just like in the last video. It's strange that it only does it for the first touch point and not for the others e.g. removing touchpoint 2 of 3 and adding it back.

**Comment by MUL7ii** [comment]
@larry104  could you debug the latest commit https://github.com/MULTidll/raylib/tree/test ?

**Comment by larry104** [comment]
I am sorry, I totally missed that you had another version ready. I just tested it and it look really good!!! I can't find any issues with the minimal test case I have.

**Comment by raysan5** [comment]
@larry104 thanks for testing and verifying it fixes the issue!

@MULTidll please, could you send a PR with the fix?

**Comment by MUL7ii** [comment]
@raysan5 yep , done #5447
