### ISSUE TITLE
[rtextures] DDS files with mipmaps render as black

### ISSUE THREAD

**Issue by Brfy** [raysan5/raylib#5416]
### Issue description

I was trying to load a DDS image with mipmaps and BC3 compression, but it renders as a black square. I tried multiple DDS exporters, one of them even made raylib crash without an error but I can't reproduce that one anymore for some reason. Whats really weird is that if I use a DDS that has no mipmaps, it renders normally.

### Environment

Desktop, Windows 10, 3.3 but also tested one 2.1, GTX 1070 TI driver 581.57

### Issue Screenshot

<img width="802" height="629" alt="Image" src="https://github.com/user-attachments/assets/3169c1a9-13ca-4f7d-962f-97fe0a6ae339" />

### Code Example

`
#include "raylib.h"

int main(void)
{
    InitWindow(800, 600, "raylib dds is broken");
    Texture2D texture = LoadTexture("dds_image.dds");

    while (!WindowShouldClose())
    {
        BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawTexture(texture, 144, 172, WHITE);
        EndDrawing();
    }
    UnloadTexture(texture);
    CloseWindow();
    return 0;
}
`

Here is the image I tried using:
https://www.mediafire.com/file/vf3gcv7n77rpqse/dds_image.dds/file

**Comment by casperbear** [comment]
I had issues with mipmaps just recently, also got black renders for images with embedded mipmaps. raysan5 fixed it. https://github.com/raysan5/raylib/issues/5400
Could you pls try to use raylib build from master.

**Comment by Brfy** [comment]
> I had issues with mipmaps just recently, also got black renders for images with embedded mipmaps. raysan5 fixed it. [#5400](https://github.com/raysan5/raylib/issues/5400) Could you pls try to use raylib build from master.

I used the latest master and it still shows a black square

**Comment by raysan5** [comment]
@Brfy It should be fixed now, one of the smaller mipmap levels was not properly sized so the texture became incomplete and setting the `GL_LINEAR_MIPMAP_LINEAR` filter made it draw black.

**Comment by casperbear** [comment]
@raysan5 rl_load_dds_from_memory doesn't utilize rlGetPixelDataSize though. It uses math limit
```
if (header->mipmap_count > 1) data_size = data_size + data_size/3;
```
(I didn't test, just leaving it here in case it still doesn't work)

**Comment by Brfy** [comment]
@raysan5 The update fixed it for that one texture but I tried it for other textures that aren't 512x256 and it still shows black

**Comment by raysan5** [comment]
@Brfy could you share some other failing textures?

**Comment by Brfy** [comment]
@raysan5 This one is 2048x512 https://www.mediafire.com/file/2tmiwk5ws7azq35/dds_image.dds/file

**Comment by raysan5** [comment]
@Brfy Redesigned how the sizee is calculated, now it should work
