### ISSUE TITLE
[shapes] DrawPolyEx() not working in latest build

### ISSUE THREAD

**Issue by hurffdurff** [raysan5/raylib#702]
The following code draws a triangle in 2.0.0 but in 2.2-dev doesn't display anything at all for me. Though it doesn't give any errors either:
Vector2 vec[] = { { 0,0 }, { 0, 200 }, { 200, 200 } };
DrawPolyEx( vec, 3, BLUE);

**Comment by raysan5** [comment]
Corrected in commit https://github.com/raysan5/raylib/commit/92f68ac6be5b85b85ebab64841c8322405e08d51

**Comment by hurffdurff** [comment]
Thanks for looking into it Ray. Your commit does fix DrawPolyEx but it seems to interfere with texture drawing now.
I’ve put DrawPolyEx into the textures_logo_raylib.c example and the code below produces a garbled image for me:
```
#include "raylib.h"
int main() {
    int screenWidth = 800;
    int screenHeight = 450;
    InitWindow(screenWidth, screenHeight, "raylib [textures] example - texture loading and drawing");
    Texture2D texture = LoadTexture("resources/raylib_logo.png");    
    while (!WindowShouldClose())   {
        BeginDrawing();
            ClearBackground(RAYWHITE);

	    Vector2 vec[] = { { 0,0 }, { 0, 200 }, { 200, 200 } };
	    DrawPolyEx( vec, 3, BLUE);
			
            DrawTexture(texture, screenWidth/2 - texture.width/2, screenHeight/2 - texture.height/2, WHITE);
            DrawText("this IS a texture!", 360, 370, 10, GRAY);
        EndDrawing();
    }
    UnloadTexture(texture);  
    CloseWindow();         
    return 0;
}
```

**Comment by raysan5** [comment]
Hopefully, corrected in commit https://github.com/raysan5/raylib/commit/af4a177af41064db5ebf9a28dcac9eb178cd7fa9.

Thanks for reporting this side case, it was a specific situation (draw just a triangle before a quad).

**Comment by hurffdurff** [comment]
Sorry, but I’m still seeing some problems with this. It has to do with doing lots of DrawPolyEx combined with DrawTextures.
The following code uses DrawPolyEx and DrawTexture 129 times before displaying the result. What I get is a white square instead of the raylib logo texture on the last texture rendered:
```
#include "raylib.h"
int main() {
    int screenWidth = 800;
    int screenHeight = 450;
    InitWindow(screenWidth, screenHeight, "raylib [textures] example - texture loading and drawing");
    Texture2D texture = LoadTexture("resources/raylib_logo.png");        

    while (!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(RAYWHITE);
	    Vector2 vec[] = { { 0,0 }, { 0, 200 }, { 200, 200 } };

		for( int i = 0; i < 129; i++ ) {
			DrawPolyEx( vec, 3, BLUE );
            DrawTexture(texture, screenWidth/2 - texture.width/2 + i , screenHeight/2 - texture.height/2 + i , WHITE);
	}
        EndDrawing();
    }
    UnloadTexture(texture);       
    CloseWindow();               
    return 0;
}
```
DrawTexture offsets slight using “i” every time so you can tell it’s just the last texture that doesn’t get displayed.
If you change it to only draw 128 times the problem disappears but above that some of the textures only displays a white square. It seems to be related to DrawPolyEx since if I replace that with DrawTriangle everything works.
I’m making a racing game where the road is drawn in segments using DrawPolyEx so I call it upwards of 1000 times every frame combined with lots of calls to DrawTexture for sprites. That’s how I found it.

**Comment by raysan5** [comment]
Ouch! What a nightmare! :P 
Ok, that's related to internal system of registering draw calls and also this:
```c
#define MAX_DRAWCALL_REGISTERED 256
```
`DrawPolyEx()` uses TRIANGLES and `DrawTexture()` uses QUADS, when changing from one to the other, a new draw call is registered, that limit is not supposed to be hit... it's more common to fill the buffers first and everything is reseted accordingly at that point... but your specific configuration forces that limit, quite interesting you found it!

There is a specific check to avoid that overflow but it seems not to trigger properly... I'll check it.

In the meantime, just a recommendation, better use:
```c
for (int i = 0; i < 200; i++) DrawPolyEx(vec, 3, BLUE);
for (int i = 0; i < 200; i++) DrawTexture(texture, screenWidth/2 - texture.width/2 + i , screenHeight/2 - texture.height/2 + i , WHITE);
```
It will reduce draw calls from `256+` to `2`, it's a good optimization.

**Comment by raysan5** [comment]
> Does this have something to do with some architectural change since it worked in 2.0.0?

Yes, I replaced the 3 separate internal buffers (LINES, TRIANGLES, QUADS) by a single one to optimize and simplify lot of redundant code (and other related problems of dealing with 3 separate buffers), consequently and as expected, new issues were introduced. You could be lazy before because data was internally directed to different buffers but, for example LINES were always drawn in front of QUADS and QUADS in front of TRIANGLES, that was the buffers processing order... Also, dealing with 3 buffers implied several extra context changes that now are avoided with a single buffer.

Already corrected `DrawPolyEx()` issue on commit https://github.com/raysan5/raylib/commit/95d3f24c686c09c458bedeb6486ffc75dfda4170.

**Comment by MontyHimself** [comment]
It seems like this is broken again. I'm on the latest git commit. Also, DrawPolyLines() is not drawing all the lines for a closed polygon, the last line connecting the end and the start is missing.

**Comment by raysan5** [comment]
@MontyHimself please, could you provide a code example? thanks!

**Comment by MontyHimself** [comment]
@raysan5 Sure, here you go:

```c
#include "raylib.h"

int main(void) {
	InitWindow(400, 400, "example");
	
	Vector2 points[3] = {
		{100, 100},
		{200, 100},
		{100, 200}
	};

	while (!WindowShouldClose()) {
		BeginDrawing();
		ClearBackground(RAYWHITE);
		DrawPolyEx(points, 3, BLUE);
		DrawPolyExLines(points, 3, RED);
		EndDrawing();
	}

	CloseWindow();
	return 0;
}
```

![raylib-rexample](https://user-images.githubusercontent.com/16304918/56096007-cdce9b00-5ee2-11e9-9615-db0838b67622.png)

**Comment by raysan5** [comment]
I checked it and it's working as expected but probably function names are not descriptive enough...

1. About `DrawPolyEx()`, points are expected to be provided definning counter-clock-wise order triangles. flip second and third point and you will get the triangle drawn.

2. About `DrawPolyExLines()`, it just connects every point with the next one, and that's what it does.

As said probably the naming of those functions should be reviewed... another related issue was also introduced some days ago: https://github.com/raysan5/raylib/issues/797

Opening a related issue:
