### ISSUE TITLE
[build] Can't build raylib on macOS

### ISSUE THREAD

**Issue by gala2000** [raysan5/raylib#840]
Hello,

I'm trying to build raylib on my mac for 10 hours:( but I get again and again the same error, as soon as I enter 

`make PLATFORM=PLATFORM_DESKTOP`

I get the following error. I realy hope someone kann help me:( i need raylib for a Project in the university 

> clang -c rglfw.c -O1 -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -Werror=implicit-function-declaration -x objective-c -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
In file included from rglfw.c:54:
In file included from ./external/glfw/src/context.c:28:
In file included from ./external/glfw/src/internal.h:183:
In file included from ./external/glfw/src/cocoa_platform.h:30:
In file included from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:24:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:27:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Headers/ATS.h:28:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Headers/ATSLayoutTypes.h:28:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Headers/ATSTypes.h:24:
In file included from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGGeometry.h:8:
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:282:78: error: 
      'swift_name' attribute cannot be applied to this declaration
  ...CF_BRIDGED_TYPE(id) __IOSurface *IOSurfaceRef __attribute__((swift_name(...
                                                                  ^
In file included from rglfw.c:111:
./external/glfw/src/cocoa_init.m:77:5: error: use of undeclared identifier
      'NSString'; did you mean 'cString'?
    NSString* appName = nil;
    ^~~~~~~~
    cString
/System/Library/Frameworks/Carbon.framework/Frameworks/OpenScripting.framework/Headers/ASRegistry.h:212:3: note: 
      'cString' declared here
  cString                       = cStringClass /* old name for cStringCl...
  ^
In file included from rglfw.c:111:
./external/glfw/src/cocoa_init.m:77:15: error: use of undeclared identifier
      'appName'; did you mean 'pName'?
    NSString* appName = nil;
              ^~~~~~~
              pName
/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AERegistry.h:478:3: note: 
      'pName' declared here
  pName                         = 'pnam' /*  0x706e616d  */
  ^
In file included from rglfw.c:111:
./external/glfw/src/cocoa_init.m:77:23: error: expression is not assignable
    NSString* appName = nil;
    ~~~~~~~~~~~~~~~~~ ^
./external/glfw/src/cocoa_init.m:78:5: error: use of undeclared identifier
      'NSDictionary'; did you mean 'UseDictionary'?
    NSDictionary* bundleInfo = [[NSBundle mainBundle] infoDictionary];
    ^~~~~~~~~~~~
    UseDictionary
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/SpeechSynthesis.framework/Headers/SpeechSynthesis.h:1504:1: note: 
      'UseDictionary' declared here
UseDictionary(
^
In file included from rglfw.c:111:
./external/glfw/src/cocoa_init.m:78:5: warning: 'UseDictionary' is deprecated:
      first deprecated in OS X 10.8 [-Wdeprecated-declarations]
    NSDictionary* bundleInfo = [[NSBundle mainBundle] infoDictionary];
    ^
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/SpeechSynthesis.framework/Headers/SpeechSynthesis.h:1504:1: note: 
      'UseDictionary' has been explicitly marked deprecated here
UseDictionary(
^
In file included from rglfw.c:111:
./external/glfw/src/cocoa_init.m:78:19: error: use of undeclared identifier
      'bundleInfo'
    NSDictionary* bundleInfo = [[NSBundle mainBundle] infoDictionary];
                  ^
./external/glfw/src/cocoa_init.m:78:32: error: expected expression
    NSDictionary* bundleInfo = [[NSBundle mainBundle] infoDictionary];
                               ^
./external/glfw/src/cocoa_init.m:79:5: error: use of undeclared identifier
      'NSString'; did you mean 'cString'?
    NSString* nameKeys[] =
    ^~~~~~~~
    cString
/System/Library/Frameworks/Carbon.framework/Frameworks/OpenScripting.framework/Headers/ASRegistry.h:212:3: note: 
      'cString' declared here
  cString                       = cStringClass /* old name for cStringCl...
  ^
In file included from rglfw.c:111:
./external/glfw/src/cocoa_init.m:79:24: error: expected expression
    NSString* nameKeys[] =
                       ^
./external/glfw/src/cocoa_init.m:79:15: error: use of undeclared identifier
      'nameKeys'
    NSString* nameKeys[] =
              ^
./external/glfw/src/cocoa_init.m:80:5: error: expected expression
    {
    ^
./external/glfw/src/cocoa_init.m:88:29: error: use of undeclared identifier
      'nameKeys'
    for (i = 0;  i < sizeof(nameKeys) / sizeof(nameKeys[0]);  i++)
                            ^
./external/glfw/src/cocoa_init.m:88:48: error: use of undeclared identifier
      'nameKeys'
    for (i = 0;  i < sizeof(nameKeys) / sizeof(nameKeys[0]);  i++)
                                               ^
./external/glfw/src/cocoa_init.m:90:19: error: use of undeclared identifier
      'bundleInfo'
        id name = bundleInfo[nameKeys[i]];
                  ^
./external/glfw/src/cocoa_init.m:90:30: error: use of undeclared identifier
      'nameKeys'
        id name = bundleInfo[nameKeys[i]];
                             ^
./external/glfw/src/cocoa_init.m:92:13: error: expected expression
            [name isKindOfClass:[NSString class]] &&
            ^
./external/glfw/src/cocoa_init.m:95:13: error: use of undeclared identifier
      'appName'
            appName = name;
            ^
./external/glfw/src/cocoa_init.m:100:10: error: use of undeclared identifier
      'appName'; did you mean 'pName'?
    if (!appName)
         ^~~~~~~
         pName
/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AERegistry.h:478:3: note: 
      'pName' declared here
  pName                         = 'pnam' /*  0x706e616d  */
  ^
In file included from rglfw.c:111:
./external/glfw/src/cocoa_init.m:104:13: error: use of undeclared identifier
      'appName'
            appName = @(*progname);
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [rglfw.o] Error 1

**Comment by iskolbin** [comment]
Ahh, I thought it's only my problem:) Well, the issue is trivial actually, `clang` can't compile objective-c sources (GLFW in our case) if file extension is `.c` not `.m`. So my solution (rather primitive):

1. Create `src/rglfw.m` with just 1 line:
```c
#include "rglfw.c"
```

2. Edit `src/Makefile`:
```diff
diff --git a/src/Makefile b/src/Makefile
index c50d4279..534f343b 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -496,8 +496,13 @@ core.o : core.c raylib.h rlgl.h utils.h raymath.h camera.h gestures.h
        $(CC) -c $< $(CFLAGS) $(INCLUDE_PATHS) -D$(PLATFORM) -D$(GRAPHICS)

 # Compile rglfw module
+ifeq ($(PLATFORM_OS),OSX)
+rglfw.o : rglfw.m
+       $(CC) -c $< $(CFLAGS) $(GLFW_CFLAGS) $(INCLUDE_PATHS) -D$(PLATFORM) -D$(GRAPHICS)
+else
 rglfw.o : rglfw.c
        $(CC) -c $< $(CFLAGS) $(GLFW_CFLAGS) $(INCLUDE_PATHS) -D$(PLATFORM) -D$(GRAPHICS)
+endif

 # Compile shapes module
 shapes.o : shapes.c raylib.h rlgl.h
```

**Comment by a3f** [comment]
> Well, the issue is trivial actually, clang can't compile objective-c sources (GLFW in our case) if file extension is .c not .m.

or pass `-x objective-c` to clang when compiling `rglfw.c`, which has the same effect. That's what the CMake build used to do[1].



[1]: Currently, we don't use `rglfw.c` at all in CMake, but reuse the CMake build scripts inside `src/external/glfw`.

**Comment by gala2000** [comment]
![makefile](https://user-images.githubusercontent.com/22816576/57933742-55cb0a80-78be-11e9-8242-49f2034dc7a5.jpeg)
a part looks like this, but I do not know where to insert the first part. I am very sorry I am a newbie:(

**Comment by iskolbin** [comment]
@a3f @gala2000 In Makefile we have
```
ifeq ($(PLATFORM),PLATFORM_DESKTOP)
     ifeq ($(PLATFORM_OS),OSX)
         # OSX default compiler
         CC = clang
         GLFW_CFLAGS = -x objective-c
...
```
and also look in the build stdout:
```
clang -c rglfw.c -O1 -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -Werror=implicit-function-declaration -x objective-c -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
```
i.e. `-x objective-c` is defined. After some digging I found, that the correct flag is `-ObjC` (at least for my compiler `Apple LLVM version 10.0.1 (clang-1001.0.46.4)`. So to fix this issue only Makefile change is needed:
```diff
diff --git a/src/Makefile b/src/Makefile
index 379b5635..d4197609 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -221,7 +221,7 @@ ifeq ($(PLATFORM),PLATFORM_DESKTOP)
     ifeq ($(PLATFORM_OS),OSX)
         # OSX default compiler
         CC = clang
-        GLFW_CFLAGS = -x objective-c
+        GLFW_CFLAGS = -ObjC
     endif
     ifeq ($(PLATFORM_OS),BSD)
         # FreeBSD, OpenBSD, NetBSD, DragonFly default compiler
```

**Comment by gala2000** [comment]
I’m really sry, i can’t understand what this part means 

diff --git a/src/Makefile b/src/Makefile
index 379b5635..d4197609 100644
--- a/src/Makefile
+++ b/src/Makefile

The other changes I’ve already done 

I am grateful that you give so much effort

**Comment by iskolbin** [comment]
@gala2000 it's diff, i.e. difference between old and new file contents, if you make changes in sources in the repo and type `git diff` you'll see this diffs. For details it's better to read `man git-diff`.  Just some notes:
* `diff --git a/src/Makefile b/src/Makefile` changed file `src/Makefile`
* `@@ -221,7 +221,7 @@ ifeq ($(PLATFORM),PLATFORM_DESKTOP)` 221 is line where to look
* ```diff
   -        GLFW_CFLAGS = -x objective-c
   +        GLFW_CFLAGS = -ObjC
   ``` 
    is the change: removed line `GLFW_CFLAGS = -x objective-c` added line `GLFW_CFLAGS = -ObjC`

**Comment by gala2000** [comment]
Thank you for the answer but now i get this messages:((((

[error.txt](https://github.com/raysan5/raylib/files/3192439/error.txt)

**Comment by a3f** [comment]
> Thank you for the answer but now i get this messages:((((

```
mkdir build
cd build
cmake ..
make
make install
```

to build/install using CMake. That should get you going till we get ahold of the plain Makefile issues. If you want to create your own CMake based project, check out https://github.com/raysan5/raylib/wiki/Working-with-CMake

**Comment by gala2000** [comment]
I had already installed CMake with homebrew, it doesn’t work:(

**Comment by a3f** [comment]
What error did you get when running CMake? I've just pushed a new commit for the Makfile, can you try it out?

**Comment by gala2000** [comment]
@a3f Ive tried with the new makefile I still get errors again:(
[ERRORnew.txt](https://github.com/raysan5/raylib/files/3192787/ERRORnew.txt)

**Comment by a3f** [comment]
I suspect, you've an old clang version. What does `clang --version` say? Also what error did you get when running CMake?

**Comment by iskolbin** [comment]
@a3f Oh, sorry for inconvenience. I cannot test it right now, have only linux at home. By the way from the documentation you linked:
```
-ObjC
Treat source input files as Objective-C inputs
```
so it should work. Alas it's not as you say. And this flag is supported at least since clang 5.0 http://releases.llvm.org/5.0.0/tools/clang/docs/ClangCommandLineReference.html. Very strange.

**Comment by a3f** [comment]
@iskolbin It seems `-ObjC` and `-x objective-c` are equivalent, except for that `-Objc` might be interpreted as `-O bjc` in some cases. The problem was elsewhere. See the comments over at the #841 for more information.

**Comment by gala2000** [comment]
@a3f thats the version and i dont get any errors if I start Cmake

> Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin16.7.0
Thread model: posix

@iskolbin how can I test this:/

someone would like to look at this with Teamviewer :)

**Comment by a3f** [comment]
>  i dont get any errors if I start Cmake

No errors at all when following the steps I posted above? So why not use CMake for now? You can choose if you want to build with the Makefile or have CMake generate the build files.

**Comment by gala2000** [comment]
I think I misunderstood the whole story with CMake. I just can not get it. I'm so desperate

**Comment by iskolbin** [comment]
@gala2000 I could try TeamViewer if you wish

**Comment by gala2000** [comment]
@iskolbin Of course, I would be so grateful to you

**Comment by iskolbin** [comment]
@gala2000 Well, write on my mail I guess(see profile)

**Comment by a3f** [comment]
You guys figured it out? Anything we should change?

**Comment by iskolbin** [comment]
@a3f It turned out gala2000 had old Mac and the problem as I can understand: development headers for Carbon which is used in GLFW are updated and using modern ObjC features(`class` for instance which is Clang 7.3) which is unsupported in older Clang(7.0) which is installed on the system. Unfortunately it's not that easy to update Clang, cos naturally it's updating with XCode. And XCode cannot be updated (natively by AppStore) 'cos system is old. Boom. So it's not problem with raylib/glwf it's apple device end of life problem. But I'll test your changes on my work Mac tomorrow and after that I guess we should close the issue.

**Comment by iskolbin** [comment]
@a3f yep, everything's working, you could close the issue

**Comment by a3f** [comment]
Glad you guys got it working. :-)
