### ISSUE TITLE
[models] Unable to load OBJ files.

### ISSUE THREAD

**Issue by RowV** [raysan5/raylib#944]
I am having issue with Raspberry PI 3. None of the examples with OBJ models are loading mesh. The screen is either white with FPS or just white cube with FPS and grid. Happening with all the examples with OBJ files. Eg: tracelog of *models_obj_loading* :
```
pi@raspberrypi:~/Raylib/examples $ ./models/models_obj_loading 
INFO: Initializing raylib 2.6-dev
INFO: UPSCALING: Required screen size: 800 x 450 -> Display size: 800 x 480
INFO: Display device initialized successfully
INFO: Display size: 800 x 480
INFO: Render size: 800 x 480
INFO: Screen size: 800 x 450
INFO: Viewport offsets: 0, 30
INFO: GPU: Vendor:   Broadcom
INFO: GPU: Renderer: VideoCore IV HW
INFO: GPU: Version:  OpenGL ES 2.0
INFO: GPU: GLSL:     OpenGL ES GLSL ES 1.00
INFO: Number of supported extensions: 1
WARNING: [EXTENSION] VAO extension not found, VAO usage not supported
WARNING: [EXTENSION] NPOT textures extension not found, limited NPOT support (no-mipmaps, no-repeat)
INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [SHDR ID 1] Shader compiled successfully
INFO: [SHDR ID 2] Shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: Internal buffers initialized successfully (CPU)
INFO: Internal buffers uploaded successfully (GPU)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Opening input device [/dev/input/event1] (mouse gamepad keyboard )
INFO: Opening input device [/dev/input/event0] (mouse )
WARNING: Gamepad device could not be opened, no gamepad available
WARNING: Could not change keyboard mode (SSH keyboard?)
INFO: [resources/models/castle.obj] Model loaded successfully in RAM (CPU)
WARNING: [resources/models/castle.obj] No meshes can be loaded, default to cube mesh
INFO: [VBOs] Mesh uploaded successfully to VRAM (GPU)
WARNING: [resources/models/castle.obj] No materials can be loaded, default to white material
WARNING: [resources/models/castle_diffuse.png] Image could not be loaded
WARNING: Texture could not be created
INFO: Target time per frame: 16.667 milliseconds
INFO: [VBO ID 5] Unloaded model vertex data from VRAM (GPU)
INFO: [VBO ID 6] Unloaded model vertex data from VRAM (GPU)
INFO: [VBO ID 7] Unloaded model vertex data from VRAM (GPU)
INFO: [VBO ID 8] Unloaded model vertex data from VRAM (GPU)
INFO: Unloaded model data from RAM and VRAM
INFO: [TEX ID 2] Unloaded texture data from VRAM (GPU)
INFO: [TEX ID 1] Unloaded texture data (base white texture) from VRAM
INFO: Window closed successfully
```
----
But what is puzzling me is that even after checking out **raylib 2.5.0** the problem still persists. But I have **old** (raylib 2.5) **compiled** static library and header file viz, *libraylib.a* and *raylib.h* in my own project folder where the obj models are loading without any problem, here is the trace log:
```
INFO: Initializing raylib 2.5
INFO: UPSCALING: Required screen size: 800 x 450 -> Display size: 800 x 480
INFO: Display device initialized successfully
INFO: Display size: 800 x 480
INFO: Render size: 800 x 480
INFO: Screen size: 800 x 450
INFO: Viewport offsets: 0, 30
INFO: GPU: Vendor:   Broadcom
INFO: GPU: Renderer: VideoCore IV HW
INFO: GPU: Version:  OpenGL ES 2.0
INFO: GPU: GLSL:     OpenGL ES GLSL ES 1.00
INFO: Number of supported extensions: 13
WARNING: [EXTENSION] VAO extension not found, VAO usage not supported
INFO: [EXTENSION] NPOT textures extension detected, full NPOT textures supported
INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [SHDR ID 1] Shader compiled successfully
INFO: [SHDR ID 2] Shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: Internal buffers initialized successfully (CPU)
INFO: Internal buffers uploaded successfully (GPU)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Opening input device [/dev/input/event1] (mouse gamepad keyboard )
INFO: Opening input device [/dev/input/event0] (mouse )
WARNING: Gamepad device could not be opened, no gamepad available
WARNING: Could not change keyboard mode (SSH keyboard?)
TINYOBJ: Error reading file 'vespa1.mtl': No such file or directory (2)
TINYOBJ: Failed to parse material file 'vespa1.mtl': -3
INFO: [resources/vespa1.obj] Model data loaded successfully: 6 meshes / 0 materials
INFO: [resources/vespa1.obj] Model loaded successfully in RAM (CPU)
INFO: [VBOs] Mesh uploaded successfully to VRAM (GPU)
WARNING: [resources/vespa1.obj] No materials can be loaded, default to white material
INFO: [resources/vespa1.png] Image loaded successfully (1200x1200)
INFO: [TEX ID 3] Texture created successfully (1200x1200 - 1 mipmaps)
INFO: Target time per frame: 16.667 milliseconds
INFO: [TEX ID 3] Unloaded texture data from VRAM (GPU)
INFO: [VBO ID 5] Unloaded model vertex data from VRAM (GPU)
INFO: [VBO ID 6] Unloaded model vertex data from VRAM (GPU)
INFO: [VBO ID 7] Unloaded model vertex data from VRAM (GPU)
INFO: Unloaded model data from RAM and VRAM
INFO: [TEX ID 2] Unloaded texture data from VRAM (GPU)
INFO: [TEX ID 1] Unloaded texture data (base white texture) from VRAM
INFO: Window closed successfully

```
NOTE : I have tried it on both Raspbian GNU/Linux 9 (stretch) and latest Raspbian Buster both have same issue.

Here is my system info:
```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by raysan5** [comment]
@RowV Thanks for reporting, project was related to an error on 3d projection setup (only on RPI native mode), corrected in commit https://github.com/raysan5/raylib/commit/ef3b01dffc964c04b83d08211ff133e22af6059b.

**Comment by RowV** [comment]
@raysan5 This bug is back on my raspberry pi with the latest raylib. Should I open a new issue?

**Comment by raysan5** [comment]
@RowV yes, it could be related to recent changes on drawing color...

**Comment by RowV** [comment]
@raysan5 opened new issue #998 as per your instruction.

**Comment by raysan5** [comment]
@RowV ok, great
